ALTER TABLE users
ADD COLUMN IF NOT EXISTS phone_country_code VARCHAR(8) NULL,
ADD COLUMN IF NOT EXISTS phone_number VARCHAR(40) NULL,
ADD COLUMN IF NOT EXISTS default_country VARCHAR(80) NULL,
ADD COLUMN IF NOT EXISTS default_address_line1 VARCHAR(255) NULL,
ADD COLUMN IF NOT EXISTS default_address_line2 VARCHAR(255) NULL,
ADD COLUMN IF NOT EXISTS default_city VARCHAR(120) NULL,
ADD COLUMN IF NOT EXISTS default_state_province VARCHAR(120) NULL,
ADD COLUMN IF NOT EXISTS default_postal_code VARCHAR(30) NULL,
ADD COLUMN IF NOT EXISTS default_delivery_note TEXT NULL;
